services:
  db:
    image: mysql:9.7
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./docker/php/DOCKERFILE
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: DOCKERFILE
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge